---
- name: Yum Install Packages
  yum:
    name: 
     - wget
    state: latest

- name: terraform install
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
    dest: /usr/bin
    remote_src: True
