
---
- name: Install Pip Packages
  hosts: localhost
  connection: localhost
  gather_facts: False
  become: true
  tasks:
    - name: Yum Install Packages
      yum:
        name: 
        - python3
        - python3-pip
        state: latest
    - name: Install package with Pip
      pip:
        name: ibm-vpc>=0.7.0
        
