- hosts: localhost
  connection: localhost
  vars:
    vms_path: "/Users/jtpape/Virtual\ Machines.localized"
    vmname: "a-new-vm"
    src_vmx:  "{{ vms_path }}/Red Hat Enterprise Linux 8 64-bit.vmwarevm/Red Hat Enterprise Linux 8 64-bit.vmx"
    dest_vmx: "{{ vms_path }}/{{ vmname }}.vmwarevm/{{ vmname }}.vmx"
  tasks:

  - name: check if vm exists
    stat:
      follow: yes
      path: "{{ dest_vmx }}"
    register: stat_result

  - name: "clone virtual machine"
    command: vmrun -T fusion clone "{{ src_vmx }}" "{{ dest_vmx }}" linked -cloneName="{{ vmname }}" -snapshot="Ready For Dev"
    when: stat_result.stat.exists == false

  - name: "start virtual machine"
    command: vmrun -T fusion start "{{ dest_vmx }}"

  - name: "get ip address"
    command: vmrun -T fusion getGuestIPAddress "{{ dest_vmx }}" -wait
    register: ip_address
    tags: sshconfig 

  - name: "set fact: ip"
    set_fact:
      ip: "{{ ip_address.stdout }}"
    tags: sshconfig

  - name: "print ip address"
    debug:
      msg: "VM IP: {{ ip_address.stdout }}, VM Cockpit http://{{ ip_address.stdout }}"

  - name: "update vm hostname"
    command: vmrun -gu root -gp {{ pw }}  -T fusion runProgramInGuest "{{ dest_vmx }}" /usr/bin/hostnamectl set-hostname {{ vmname }}

  - name: "ensure vm is registered with RHSM"
    command: vmrun -gu root -gp {{ pw }} -T fusion runProgramInGuest "{{ dest_vmx }}" /usr/sbin/subscription-manager register --activationkey=devbox --org="{{ rhorg }}" --force
    register: rhsm_out
    tags: register

  - name: "ensure local private key exists on VM"
    command: vmrun -gu root -gp {{ pw }} -T fusion CopyFileFromHostToGuest "{{ dest_vmx }}" ~/.ssh/id_rsa /root/.ssh/id_rsa
    tags: sshconfig

  - name: "display RHSM result"
    debug:
      msg: "{{ rhsm_out }}"

  - name: "add vm to ssh config"
    blockinfile:
      dest: ~/.ssh/config
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
      block: |
        Host {{ ip }}
          HostName {{ ip }}
          User root
          Port 22
          UserKnownHostsFile /dev/null
          StrictHostKeyChecking no
          PasswordAuthentication yes
          ForwardAgent yes
          LogLevel FATAL
    tags: sshconfig